import styles from '@/styles/components/Layout.module.scss'
import Head from 'next/head'
import Footer from './Footer'
import Header from './Header'
import ScrollBackToTopButton from './ScrollBackToTopButton'

const Layout = ({ children, title }) => {
	return (
		<>
			<Head>
				<title>{title ? title + ' - Online Shop' : 'Online Shop'}</title>
				<meta name='description' content='Generated by create next app' />
				<meta
					name='viewport'
					content='width=device-width, initial-scale=1'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<div className={styles.mainWrapper}>
				<Header />
				<ScrollBackToTopButton />
				{children}
				<Footer />
			</div>
		</>
	)
}
export default Layout
